=== qiqiguana/candor/data/EvoSuiteBenchmark/original/83_xbus/src/main/resources/dtd/Address.dtd
<!ELEMENT Address ( Company+ ) >

<!ELEMENT Company ( Name+, Employee+ ) >

<!ELEMENT Employee ( Name, Rank ) >

<!ELEMENT Name ( #PCDATA ) >

<!ELEMENT Rank ( #PCDATA ) >

=== qiqiguana/candor/data/EvoSuiteBenchmark/original/83_xbus/src/test/resources/input/Test0001Infile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Address SYSTEM "Address.dtd">
<Address>
	<Company>
		<Name>xyz Corp.</Name>
		<Employee>
			<Name>John Doe</Name>
			<Rank>Software Engineer</Rank>
		</Employee>
		<Employee>
			<Name>Mary Powers</Name> 
			<Rank>Senior Software Engineer</Rank>
		</Employee>
	</Company>
</Address>
